package ua.nure.lymar.airlines.util;

public class Commands {
    public static final String USERLIST_COMMAND = "/admin/userlist.html";
    public static final String USERSAVE_COMMAND = "/admin/usersave.html";
    public static final String USEREDIT_COMMAND = "/admin/useredit.html";
    public static final String USERDELETE_COMMAND = "/admin/userdelete.html";
    public static final String USEREDITPASS_COMMAND = "/userpasswordedit.html";
    public static final String USERSAVEPASS_COMMAND = "/userpasswordsave.html";
    public static final String USERSETDEFPASS_COMMAND = "/admin/userpassworddefault.html";
    public static final String STAFFLIST_COMMAND = "/dispetcher/stafflist.html";
    public static final String STAFFSAVE_COMMAND = "/dispetcher/staffsave.html";
    public static final String STAFFEDIT_COMMAND = "/dispetcher/staffedit.html";
    public static final String STAFFDELETE_COMMAND = "/dispetcher/staffdelete.html";
    public static final String LOGIN_COMMAND = "/login.html";
    public static final String LOGOUT_COMMAND = "/logout.html";
    public static final String RUSLANGUAGE_COMMAND = "/ruslanguage.html";
    public static final String ENGLANGUAGE_COMMAND = "/englanguage.html";
    public static final String MAIN_COMMAND = "/";
    public static final String INDEX_PAGE_COMMAND = "/index.html";
    public static final String CREWLIST_COMMAND = "/dispetcher/crewlist.html";
    public static final String CREWEDIT_COMMAND = "/dispetcher/crewedit.html";
    public static final String CREWSAVE_COMMAND = "/dispetcher/crewsave.html";
    public static final String CREWDELETE_COMMAND = "/dispetcher/crewdelete.html";
    public static final String CREWSHOW_COMMAND = "/dispetcher/crewshow.html";
    public static final String ADDSTAFFINCREW_COMMAND = "/dispetcher/addstaffincrew.html";
    public static final String DELSTAFFFROMCREW_COMMAND = "/dispetcher/deletefromcrew.html";
    public static final String FLIGHTLIST_COMMAND = "/flightlist.html";
    public static final String FLIGHTEDIT_COMMAND = "/flightedit.html";
    public static final String FLIGHTSAVE_COMMAND = "/flightsave.html";
    public static final String FLIGHTDELETE_COMMAND = "/flightdelete.html";
    public static final String ALERT_LIST_COMMAND = "/alertlist.html";
    public static final String ALERT_EDIT_COMMAND = "/admin/alertedit.html";
    public static final String ALERT_SAVE_COMMAND = "/admin/alertsave.html";
    public static final String SORT_FLIGHTS_BYNAME_COMMAND = "/sortflightbyname.html";
    public static final String SORT_FLIGHTS_BYDATE_COMMAND = "/sortflightbydate.html";
    public static final String SORT_FLIGHTS_BYDEPARTURE_COMMAND = "/sortflightbydeparturecity.html";
    public static final String SORT_FLIGHTS_BYARRIVAL_COMMAND = "/sortflightbyarrivalcity.html";
    public static final String ALERT_TO_ADMIN_COMMAND = "/dispetcher/alerttoadmin.html";
    public static final String SAVE_MESSAGE_COMMAND = "/dispetcher/savemessage.html";
    public static final String FLIGHT_SEARCH_COMMAND = "/dispetcher/flightSearch.html";
    public static final String FLIGHT_SEARCH_RESULT_COMMAND = "/dispetcher/searchResult.html";
}
